# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMIT3UEXjbV6Kl3BLEuj-iGn0S42SLAa
"""

import streamlit as st
import pandas as pd

# -----------------------------------------------------
# CONFIGURACIÓN GENERAL
# -----------------------------------------------------

st.set_page_config(
    page_title="Dashboard ESG - ACUAMAR S.A.",
    page_icon="🌎",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -----------------------------------------------------
# LECTURA DE DATOS
# -----------------------------------------------------

@st.cache_data
def cargar_datos():

    df = pd.read_excel(
        "Datos_Sostenibilidad_Riesgos_RRHH.xlsx",
        sheet_name="sostenibilidad"
    )

    return df

from utils.carga_datos import cargar_datos

df=cargar_datos()

# -----------------------------------------------------
# SIDEBAR
# -----------------------------------------------------

with st.sidebar:

    st.image(
        "https://img.icons8.com/color/240/environment-care.png",
        width=120
    )

    st.title("Dashboard ESG")

    st.write("### ACUAMAR S.A.")

    st.divider()

    st.success("Proyecto Portafolio")

    st.write("Versión 1.0")

    st.divider()

    st.info(
        """
        Este dashboard presenta los indicadores ESG
        desarrollados para la empresa ACUAMAR S.A.
        """
    )

# -----------------------------------------------------
# PORTADA
# -----------------------------------------------------

st.title("🌎 Dashboard ESG")

st.subheader("Evaluación de Sostenibilidad Empresarial")

st.write("## ACUAMAR S.A.")

st.write("---")

st.write(
"""
Este aplicativo integra indicadores ambientales,
sociales y de gobernanza (ESG),
incluyendo análisis predictivo y escenarios
de sostenibilidad.
"""
)

st.write("")

# -----------------------------------------------------
# INFORMACIÓN GENERAL
# -----------------------------------------------------

col1,col2,col3 = st.columns(3)

with col1:

    st.metric(
        "Registros",
        len(df)
    )

with col2:

    st.metric(
        "Variables",
        len(df.columns)
    )

with col3:

    st.metric(
        "Años",
        df["Año"].nunique()
    )

st.write("---")

# -----------------------------------------------------
# VISTA PREVIA
# -----------------------------------------------------

st.subheader("Vista previa de los datos")

st.dataframe(
    df.head(),
    use_container_width=True
)

st.write("---")

# -----------------------------------------------------
# VARIABLES DISPONIBLES
# -----------------------------------------------------

st.subheader("Variables del conjunto de datos")

st.dataframe(
    pd.DataFrame(
        {
            "Variables":df.columns
        }
    ),
    use_container_width=True
)

st.write("---")

# -----------------------------------------------------
# DESCRIPCIÓN
# -----------------------------------------------------

st.subheader("Módulos del Dashboard")

c1,c2 = st.columns(2)

with c1:

    st.success("""
    ⚡ Energía

    🌍 Huella de Carbono

    💧 Huella Hídrica
    """)

with c2:

    st.success("""
    ♻️ Residuos

    ⚠️ Riesgo Ambiental

    📈 Pronósticos ESG
    """)

st.write("---")

st.caption(
    "Desarrollado en Python • Streamlit • Plotly • Prophet"
)