# -*- coding: utf-8 -*-
"""carga_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAjqqSPR03-Sgv3nnixKCohejYWneHzC
"""

import pandas as pd
import streamlit as st

@st.cache_data
def cargar_datos():

    archivo="Datos_Sostenibilidad_Riesgos_RRHH.xlsx"

    df = pd.read_excel(
        archivo,
        sheet_name="sostenibilidad"
    )

    return df